#!/bin/bash
# Enable observability (tracing and logging) for AgentCore Runtime and Memory

RUNTIME_ID="langgraph_agent_runtime-TEUJecAs2z"
MEMORY_ID="langgraph_agent_memory-QaYdO09lxb"
REGION="us-east-1"

echo "═══════════════════════════════════════════════════════════════"
echo "  AgentCore Observability Configuration"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Runtime ID: $RUNTIME_ID"
echo "Memory ID:  $MEMORY_ID"
echo "Region:     $REGION"
echo ""
echo "NOTE: As of January 2026, observability must be enabled via AWS Console."
echo "      AWS CLI commands for bedrock-agentcore observability are not yet available."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Enable Tracing via AWS Console"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Go to: https://console.aws.amazon.com/bedrock/agentcore"
echo ""
echo "2. Enable Runtime Tracing:"
echo "   • Click 'Runtimes' in the left sidebar"
echo "   • Find and click: $RUNTIME_ID"
echo "   • Click 'Edit' button"
echo "   • Enable 'Tracing'"
echo "   • Save changes"
echo ""
echo "3. Enable Memory Tracing:"
echo "   • Click 'Memory' in the left sidebar"
echo "   • Find and click: $MEMORY_ID"
echo "   • Click 'Edit' button"
echo "   • Enable 'Tracing'"
echo "   • Save changes"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  View Logs After Enabling Tracing"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Runtime logs (container stdout/stderr and errors):"
echo "  aws logs tail /aws/bedrock-agentcore/runtimes/$RUNTIME_ID-DEFAULT \\"
echo "    --follow --format short --region $REGION"
echo ""
echo "Memory API operation logs (CreateEvent, ListEvents, etc.):"
echo "  aws logs tail /aws/vendedlogs/bedrock-agentcore/memory/APPLICATION_LOGS/$MEMORY_ID \\"
echo "    --follow --format short --region $REGION"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "After enabling tracing, test your agent and check the logs above"
echo "for detailed error messages and debugging information."
echo ""
